# 核心：Mihomo
# 适用: Windows / Android

# 端口
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 9797
tproxy-port: 9898

# 通用
ipv6: true
mode: rule
log-level: info
allow-lan: true
unified-delay: true
tcp-concurrent: true
find-process-mode: strict

# 面板
external-controller: 127.0.0.1:9090
external-ui: webui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"

# 缓存
profile:
  store-selected: true
  store-fake-ip: true

# 嗅探
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

# TUN system/mixed/gvisor
tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true
  strict_route: true

# DNS
dns:
  enable: true
  prefer-h3: false
  ipv6: true
  listen: 127.0.0.1:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

# 订阅锚点
Proxy: &Proxy
  type: http
  interval: 21600
  health-check:
    enable: true
    url: "https://www.gstatic.com/generate_204"
    interval: 1800

# 订阅
proxy-providers:
  Clash:
    <<: *Proxy
    url: "订阅节点"
    path: "./proxy_provider/Clash.yaml"

# UrlTest 锚点
UrlTest: &UrlTest
  type: url-test
  interval: 1800
  tolerance: 50
  lazy: true
  url: "https://www.gstatic.com/generate_204"
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: true

# 本地策略
proxies:
  - name: 直接连接
    type: direct
  - name: 拒绝连接
    type: reject

# 策略组
proxy-groups:
  - name: 黑白名单
    type: select
    icon: "https://raw.githubusercontent.com/Orz-3/mini/master/Color/Final.png"
    proxies:
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新国节点
      - 美国节点
      - 直接连接

  # 节点筛选
  - name: 香港节点
    <<: *UrlTest
    filter: "(?i)🇭🇰|香港|HK"
    icon: "https://raw.githubusercontent.com/Esgz/icon/main/HK.png"
    use:
      - Clash

  - name: 台湾节点
    <<: *UrlTest
    filter: "(?i)🇹🇼|台湾|TW"
    icon: "https://raw.githubusercontent.com/Esgz/icon/main/TW.png"
    use:
      - Clash

  - name: 日本节点
    <<: *UrlTest
    filter: "(?i)🇯🇵|日本|JP"
    icon: "https://raw.githubusercontent.com/Esgz/icon/main/JP.png"
    use:
      - Clash

  - name: 新国节点
    <<: *UrlTest
    filter: "(?i)🇸🇬|新加坡|SG"
    icon: "https://raw.githubusercontent.com/Esgz/icon/main/SG.png"
    use:
      - Clash

  - name: 美国节点
    <<: *UrlTest
    filter: "(?i)🇺🇸|美国|US"
    icon: "https://raw.githubusercontent.com/Esgz/icon/main/US.png"
    use:
      - Clash

# 规则锚点
list: &list
  type: http
  interval: 86400
  timeout: 5000
  behavior: classical
  format: text

# 规则集
rule-providers:
  域名拦截:
    <<: *list
    url: "https://raw.githubusercontent.com/Esgz/rules/main/Reject.list"
    path: "./RuleSet/Reject.list"

  大陆服务:
    <<: *list
    url: "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Ruleset/Surge/ChinaASN.list"
    path: "./RuleSet/ChinaASN.list"

# 规则
rules:
  - RULE-SET,域名拦截,拒绝连接
  - RULE-SET,大陆服务,直接连接
  - MATCH,黑白名单